// <auto-generated />
using System;
using ICar.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ICar.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210605172255_Union")]
    partial class Union
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ICar.Infrastructure.Models.Car", b =>
                {
                    b.Property<string>("Plate")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AcceptsChange")
                        .HasColumnType("bit");

                    b.Property<int>("CityId")
                        .HasColumnType("INT");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<string>("CompanyCnpj")
                        .HasColumnType("NVARCHAR(18)");

                    b.Property<int>("GasolineType")
                        .HasColumnType("int");

                    b.Property<bool>("IpvaIsPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArmored")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLicensed")
                        .HasColumnType("bit");

                    b.Property<double>("KilometersTraveled")
                        .HasColumnType("float");

                    b.Property<int>("MakeDate")
                        .HasColumnType("int");

                    b.Property<int>("MakedDate")
                        .HasColumnType("int");

                    b.Property<string>("Maker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfViews")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("TypeOfExchange")
                        .HasColumnType("int");

                    b.Property<string>("UserCpf")
                        .HasColumnType("NVARCHAR(18)");

                    b.HasKey("Plate");

                    b.HasIndex("CityId");

                    b.HasIndex("CompanyCnpj");

                    b.HasIndex("UserCpf");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("ICar.Infrastructure.Models.City", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR(60)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("ICar.Infrastructure.Models.Company", b =>
                {
                    b.Property<string>("Cnpj")
                        .HasMaxLength(18)
                        .HasColumnType("NVARCHAR(18)");

                    b.Property<DateTime>("AccountCreationDate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("NVARCHAR(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR(60)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR(60)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR(30)");

                    b.HasKey("Cnpj");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ICar.Infrastructure.Models.CompanyCity", b =>
                {
                    b.Property<string>("CompanyCnpj")
                        .HasColumnType("NVARCHAR(18)");

                    b.Property<int>("CityId")
                        .HasColumnType("INT");

                    b.HasKey("CompanyCnpj", "CityId");

                    b.HasIndex("CityId")
                        .IsUnique();

                    b.HasIndex("CompanyCnpj")
                        .IsUnique();

                    b.ToTable("CompanyCities");
                });

            modelBuilder.Entity("ICar.Infrastructure.Models.Entities.CarImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarPlate")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageStream")
                        .IsRequired()
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("CarPlate");

                    b.ToTable("CarImages");
                });

            modelBuilder.Entity("ICar.Infrastructure.Models.Login", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyCnpj")
                        .HasColumnType("NVARCHAR(18)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("DATETIME");

                    b.Property<string>("UserCpf")
                        .HasColumnType("NVARCHAR(18)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCnpj");

                    b.HasIndex("UserCpf");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("ICar.Infrastructure.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyCnpj")
                        .HasColumnType("NVARCHAR(18)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("UserCpf")
                        .HasColumnType("NVARCHAR(18)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCnpj");

                    b.HasIndex("UserCpf");

                    b.ToTable("News");
                });

            modelBuilder.Entity("ICar.Infrastructure.Models.User", b =>
                {
                    b.Property<string>("Cpf")
                        .HasMaxLength(18)
                        .HasColumnType("NVARCHAR(18)");

                    b.Property<DateTime>("AccountCreationDate")
                        .HasColumnType("DATETIME");

                    b.Property<int>("CityId")
                        .HasColumnType("INT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("NVARCHAR(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR(60)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR(60)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR(30)");

                    b.HasKey("Cpf");

                    b.HasIndex("CityId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ICar.Infrastructure.Models.Car", b =>
                {
                    b.HasOne("ICar.Infrastructure.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ICar.Infrastructure.Models.Company", null)
                        .WithMany("Cars")
                        .HasForeignKey("CompanyCnpj");

                    b.HasOne("ICar.Infrastructure.Models.User", null)
                        .WithMany("Cars")
                        .HasForeignKey("UserCpf");

                    b.Navigation("City");
                });

            modelBuilder.Entity("ICar.Infrastructure.Models.CompanyCity", b =>
                {
                    b.HasOne("ICar.Infrastructure.Models.City", "City")
                        .WithOne()
                        .HasForeignKey("ICar.Infrastructure.Models.CompanyCity", "CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ICar.Infrastructure.Models.Company", "Company")
                        .WithOne()
                        .HasForeignKey("ICar.Infrastructure.Models.CompanyCity", "CompanyCnpj")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ICar.Infrastructure.Models.Entities.CarImage", b =>
                {
                    b.HasOne("ICar.Infrastructure.Models.Car", "Car")
                        .WithMany("CarImages")
                        .HasForeignKey("CarPlate");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("ICar.Infrastructure.Models.Login", b =>
                {
                    b.HasOne("ICar.Infrastructure.Models.Company", null)
                        .WithMany("Logins")
                        .HasForeignKey("CompanyCnpj");

                    b.HasOne("ICar.Infrastructure.Models.User", null)
                        .WithMany("Logins")
                        .HasForeignKey("UserCpf");
                });

            modelBuilder.Entity("ICar.Infrastructure.Models.News", b =>
                {
                    b.HasOne("ICar.Infrastructure.Models.Company", null)
                        .WithMany("News")
                        .HasForeignKey("CompanyCnpj");

                    b.HasOne("ICar.Infrastructure.Models.User", null)
                        .WithMany("News")
                        .HasForeignKey("UserCpf");
                });

            modelBuilder.Entity("ICar.Infrastructure.Models.User", b =>
                {
                    b.HasOne("ICar.Infrastructure.Models.City", "City")
                        .WithOne()
                        .HasForeignKey("ICar.Infrastructure.Models.User", "CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("ICar.Infrastructure.Models.Car", b =>
                {
                    b.Navigation("CarImages");
                });

            modelBuilder.Entity("ICar.Infrastructure.Models.Company", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Logins");

                    b.Navigation("News");
                });

            modelBuilder.Entity("ICar.Infrastructure.Models.User", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Logins");

                    b.Navigation("News");
                });
#pragma warning restore 612, 618
        }
    }
}
